apiVersion: v1
kind: Namespace
metadata:
  name: fddb-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fddb-operator
  namespace: fddb-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fddb-operator-role
rules:
- apiGroups: ["fddb.benni1390.github.io"]
  resources: ["fddbexporters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["fddb.benni1390.github.io"]
  resources: ["fddbexporters/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces", "secrets", "services", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fddb-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fddb-operator-role
subjects:
- kind: ServiceAccount
  name: fddb-operator
  namespace: fddb-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fddb-operator
  namespace: fddb-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fddb-operator
  template:
    metadata:
      labels:
        app: fddb-operator
    spec:
      serviceAccountName: fddb-operator
      containers:
      - name: operator
        image: ghcr.io/benni1390/fddb-exporter-operator:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
